config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#home'
  devise_for :users
  resources :houses do
    resources :addresses
  end
  resources :users, only: %i[index edit update]
  resources :cities, only: :index

  get 'users/not_approved' => 'users#not_approved', as: :not_approved
  get 'users/reserve_approval' => 'users#reserve_approval',
      as: :reserve_approval
  # get 'users/search' => 'users#search', as: :search
  get 'users/show_house/:id' => 'users#show_house', as: :show_house # user_id

  patch '/houses/approval_update/:house_id' => 'houses#approval_update',
        as: :approval_update
  patch '/houses/reserve_update/:house_id' => 'houses#reserve_update',
        as: :reserve_update
  # For details on the DSL available within this file, see
  # https://guides.rubyonrails.org/routing.html
end

app/controllers/houses_controller.rb
# frozen_string_literal: true

class HousesController < ApplicationController
  before_action :set_house, only: %i[edit update destroy]
  before_action :authenticate_user!

  def index
    @reserved = current_user.houses.where('houses.reserved=?', true)
    @not_reserved = House.where(user_id: current_user.id, reserved: false)
  end

  def show
    @house = Address.eager_load(:house)
                    .where('addresses.house_id=?', params[:id]).first
 
  end

  def new
    @house = House.new
  end

  def edit; end

  def create
    @house = House.new(house_params)
    @house.user = current_user
    respond_to do |format|
      if @house.save
        format.html { redirect_to new_house_address_path(@house) }
      else
        format.html { render :new }
      end
    end
  end

  def update
    if @house.update(house_params)
      redirect_to edit_house_address_path(@house),
                  method: :post,
                  notice: 'House Profile was successfully updated.'
    else
      render :edit
    end
  end

  def approval_update
    @house = Address.eager_load(house: :user)
                    .find_by('addresses.house_id=?', params[:house_id])
    if @house.house.approved == false
      @house.house.update(approved: true)
      BookingMailer.house_approval(@house).deliver
      redirect_to not_approved_path
    else
      @house.house.update(approved: false)
      BookingMailer.house_disapproval(@house).deliver
      redirect_to root_path
    end
  end

  def reserve_update
    @house = Address.eager_load(house: :user)
                    .find_by('addresses.house_id=?', params[:house_id])
    @house.house.update(reserved: true)
    current_user.add_role :customer
    flash[:success] = 'You will Receive Confirmation mail'
    BookingMailer.booking_confirmation(current_user, @house).deliver
    redirect_to root_path
  end

  def destroy
    @house.destroy
    redirect_to houses_url, notice: 'House was successfully destroyed.' 
  end

  private

  def set_house
    @house = House.find_by(id: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def house_params
    params.require(:house).permit(:category, :house_type, :square_feet, :amount,
                                  :reserved, :approved, images: [])
  end
end

app/views/houses/edit.html.erb
<% if @house.user_id == current_user.id %>
  <%= form_with(model: @house, local: true) do |form| %> 
    <div class="container">  
      <div class="row">
        <div class="col-md-2">
         <%= form.label :House_Type %>
        </div>
        <div class="col-md-10">
          <%= form.select :house_type, House::House_types %>
        </div>
      </div>
      
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :Category %>
        </div>
        <div class="col-md-10">
          <%= form.select :category, House::Categories %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :Square_Feet %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :square_feet %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :Amount %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :amount %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :Reserved %>
        </div>
        <div class="col-md-10">
          <%= form.radio_button(:reserved,false) %>
          <%= form.label ("false")  %>
          <%= form.radio_button(:reserved,true) %>
          <%= form.label ("true")  %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :House_Image %>
        </div>
        <div class="col-md-10">
          <%= form.file_field :images, multiple: true %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-11">
          <%= form.submit :edit_address, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>  
  <% end %>       
  <br>
  <%= link_to 'Back', houses_path %>
</div>

app/views/houses/index.html.erb
<%= link_to 'Post House', new_house_path , class: "btn btn-primary" %>

<br><br>
<h4>Houses Posted by <%= current_user.first_name %> <%= current_user.last_name %></h4>
<br>
<b>Reserved</b>

<table class="table">
  <thead class="thead-light">
    <tr>
      <th>House Type</th>
      <th>Category</th>
      <th>Square Feet</th>
      <th>Amount</th>
      <th>View</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @reserved.each do |house| %>
      <tr>
        <td><%= house.house_type %></td>
        <td><%= house.category %></td>
        <td><%= house.square_feet %></td>
        <td><%= house.amount %></td>
        <td><%= link_to 'View', house_path(house), class: "btn btn-outline-primary" %>
        <td><%= link_to 'Edit', edit_house_path(house), class: "btn btn-outline-primary" %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-outline-primary"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<b> Not Reserved </b>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>House Type</th>
      <th>Category</th>
      <th>Square Feet</th>
      <th>Amount</th>
      <th>View</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
    <% @not_reserved.each do |house| %>
      <tr>
        <td><%= house.house_type %></td>
        <td><%= house.category %></td>
        <td><%= house.square_feet %></td>
        <td><%= house.amount %></td>
        <td><%= link_to 'View', house_path(house), class: "btn btn-outline-primary" %>
        <td><%= link_to 'Edit', edit_house_path(house), class: "btn btn-outline-primary" %></td>
        <td><%= link_to 'Destroy', house, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-outline-primary"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', root_path %>

app/views/houses/new.html.erb
<% if @house.errors.any? %>

      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @house.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

  <% end %>
<%= form_with(model: @house, local: true) do |form| %> 
<div class="container">  
  <div class="row">
    <div class="col-md-2">
      <%= form.label :House_Type %>
    </div>
    <div class="col-md-10">
     <%= form.select :house_type, options_from_collection_for_select(House.select(:house_type).distinct, :house_type, :house_type), {:class=>'form-control', :onchange => "myFunction(this.value);"} %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
     <%= form.label :Category %>
    </div>
    <div class="col-md-10">
     <%= form.select :category, options_from_collection_for_select(House.select(:category).distinct, :category, :category), {:class=>'form-control', :onchange => "myFunction(this.value);"} %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :Square_Feet %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :square_feet, placeholder: "1000 sq.ft" %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :Amount %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :amount %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :House_Image %>
    </div>
    <div class="col-md-10">
      <%= form.file_field :images, multiple: true %><br><br>
    </div>
  </div>

  <br>
  
  <div class="row">
    <div class="col-md-1">
      
    </div>
    <div class="col-md-11">
    <button type="submit" class="btn btn-outline-primary">Add Address</button>
      <%#= form.submit :Add_Address %>
    </div>
  </div>
<% end %>         
<br>
<%= link_to 'Back', houses_path %>
</div>

app/views/houses/show.html.erb
<div class="display">

  <div style = "width:400px; height:400px;display: flex; flex-direction: column;">
      <% if @house.house.images.attached? %>
        <% (0...@house.house.images.count).each do |image| %>
          <%= image_tag(@house.house.images[image], style:"width:100%") %>
        <% end %>
      <% else %>
        <%= image_tag("missing.png", style:"width:100%") %>
      <% end %>
  </div>
  <div class="info">

  <p>
      <strong>Approved:</strong>
      <%= @house.house.approved %>
    </p>

    <p>
      <strong>House Type:</strong>
      <%= @house.house.house_type %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @house.house.category %>
    </p>


    <p>
      <strong>Square Feet:</strong>
      <%= @house.house.square_feet %>
    </p>

    <p>
      <strong>Amount:</strong>
      <%= @house.house.amount %>
    </p>

    <p>
      <strong>Address :</strong>
      <%= @house.house_address %>
    </p>

    <p>
      <strong>State:</strong>
      <%= CS.states(:in)[@house.state.to_sym] %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @house.city %>
    </p>

    <p>
      <strong>Area:</strong>
      <%= @house.area %>
    </p>

    
  </div>
</div>
<br>

<%= link_to 'Back', houses_path%>



  