config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#home'
  devise_for :users
  resources :houses do
    resources :addresses
  end
  resources :users, only: %i[index edit update]
  resources :cities, only: :index

  get 'users/not_approved' => 'users#not_approved', as: :not_approved
  get 'users/reserve_approval' => 'users#reserve_approval',
      as: :reserve_approval
  # get 'users/search' => 'users#search', as: :search
  get 'users/show_house/:id' => 'users#show_house', as: :show_house # user_id

  patch '/houses/approval_update/:house_id' => 'houses#approval_update',
        as: :approval_update
  patch '/houses/reserve_update/:house_id' => 'houses#reserve_update',
        as: :reserve_update
  # For details on the DSL available within this file, see
  # https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :houses
  has_many :comments
  has_many :reservations

  validates :first_name, :last_name, :contact, :birth_date, :gender,
            presence: true
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def home
    @houses = Address.eager_load(house: :user)
                     .where('houses.approved=? AND houses.reserved=?',
                            true, false)
  end

  def index
    @cities = CS.cities(params[:state])
    @houses = Address.where(city: params[:city])
    @address_cities = CS.cities(params[:address_state])
  end

  def show_house
    @house = Address.eager_load(house: :user)
                    .find_by('houses.id=?', params[:id])
  end

  def search
    @houses = Address.where(city: params[:city])
    render :home, object: @houses
  end

  def not_approved
    @approval = Address.eager_load(house: :user)
                       .where('houses.approved=?', false)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/home.html.erb
<div class="search">
    <%= form_with model: @house, method: :get do |f| %>
      <div class="row">
        <div class="col-md-5">
          <%= f.label :state %>
          
          <%= f.select :state, options_for_select(CS.states(:in).map { |c| [c[1], c[0]] } ),{:prompt => 'Select State'},class: "btn btn-outline-secondary dropdown-toggle" %>
        </div>
        <div class="col-md-7">
        <!-- State -->
          <%= f.label :city %>
          <%= f.select :city, options_for_select([] ),{:prompt => 'Select City'},class: "btn btn-outline-secondary dropdown-toggle" %>
        </div>
      </div>
    <% end %>
    
</div>
<br>
<br>

  <h3>Houses</h3>
  <table class="table">
  <thead class="thead-light">
  
    <tr>
      <th>Type</th>
      <th>Category</th>
      <th>Square feet</th>
      <th>Amount</th>
      <th>View Details</th>
    </tr>
  </thead>

  <tbody class="houses" id="houses">
    <% @houses.each do |house| %>
      <tr>
        <td><%= house.house.house_type %></td>
        <td><%= house.house.category %></td>
        <td><%= house.house.square_feet %></td>
        <td><%= house.house.amount %></td>
        <td><%= link_to 'View Details', show_house_path(house.house_id), class: "btn btn-outline-primary" %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

app/views/users/index.js.erb
<% @cities.each do |c| %>
  city.options[city.options.length] = new Option('<%= c %>', '<%= c %>')
<% end %>

<% @address_cities.each do |c| %>
  address_city.options[address_city.options.length] = new Option('<%= c %>', '<%= c %>')
<% end %>

app/views/users/not_approved.html.erb
<% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
    <div class="row">
      <div class="request">
        <%= @approval.length %>
      </div>
       Pending Request for House Approval
    </div>
  <br><br>
    <table class="table">
      <thead>
        <tr>
          <th>Type</th>
          <th>Category</th>
          <th>Square feet</th>
          <th>Amount</th>
          <th>View Details</th>
        </tr>
      </thead>

      <tbody>
        <% @approval.each do |house| %>
          <tr>
            <td><%= house.house.house_type %></td>
            <td><%= house.house.category %></td>
            <td><%= house.house.square_feet %></td>
            <td><%= house.house.amount %></td>
            <td><%= link_to 'View Details', show_house_path(house.house_id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>

app/views/users/show_house.html.erb
<br><br>
<div class="display">

  <div style = "width:400px; height:400px;display: flex; flex-direction: column;">
      
        <% if @house.house.images.attached? %>
        <% (0...@house.house.images.count).each do |image| %>
          <%= image_tag(@house.house.images[image], style:"width:100%") %>
        <% end %>
      <% else %>
        <%= image_tag("missing.png", style:"width:100%") %>
      <% end %>
  </div>
  <div class="info">
    <p>
      <strong>House Type:</strong>
      <%= @house.house.house_type %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @house.house.category %>
    </p>


    <p>
      <strong>Square Feet:</strong>
      <%= @house.house.square_feet %>
    </p>

    <p>
      <strong>Amount:</strong>
      <%= @house.house.amount %>
    </p>

    <p>
      <strong>Address :</strong>
      <%= @house.house_address %>
    </p>

    <p>
      <strong>State:</strong>
      <%= CS.states(:in)[@house.state.to_sym] %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @house.city %>
    </p>

    <p>
      <strong>Area:</strong>
      <%= @house.area %>
    </p>

    <p>
    <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
        Contact House Owner
      </a>
    </p>
  </div>
</div>
<br>




<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <h4><b>House Owner</b></h4>


    
    <p>
      <strong>Name:</strong>
      <%= @house.house.user.first_name %> <%= @house.house.user.last_name %>
    </p>

    <p>
      <strong>Email id:</strong>
      <%= @house.house.user.email %> 
    </p>

    <p>
      <strong>Contact No:</strong>
      <%= @house.house.user.contact %> 
    </p>
  </div>
</div>

<br><br>
<% if user_signed_in? %>
  <% if current_user.has_role? (:admin)%>
  
    <% if @house.house.approved == true %>
      <%= link_to 'Disapprove', approval_update_path(@house.house_id), method: :patch, class: "btn btn-outline-primary" %>
      <%= link_to 'Book', reserve_update_path(@house.house_id), method: :patch, class: "btn btn-outline-primary" %><br>
      <%= link_to 'Back', root_path %>
      <br><br>
    <% else %>
      <%= link_to 'Approve', approval_update_path(@house.house_id), method: :patch, class: "btn btn-outline-primary" %>
      <br><br>
      <%= link_to 'Back', not_approved_path %>
      <br><br>
    <% end %>
  <% else %>
    <%= link_to 'Book', reserve_update_path(@house.house_id), method: :patch, class: "btn btn-outline-primary" %>
    <br><br>
    <%= link_to 'Back', root_path %>
    <br><br>
  <%end%>
<% else %>
  <%= link_to 'Book', reserve_update_path(@house.house_id), method: :patch, class: "btn btn-outline-primary" %>
  <br><br>
  <%= link_to 'Back', root_path %>
  <br><br>
<%end%>



  