config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#home'
  devise_for :users
  resources :houses do
    resources :addresses
  end
  resources :users, only: %i[index edit update]
  resources :cities, only: :index

  get 'users/not_approved' => 'users#not_approved', as: :not_approved
  get 'users/reserve_approval' => 'users#reserve_approval',
      as: :reserve_approval
  # get 'users/search' => 'users#search', as: :search
  get 'users/show_house/:id' => 'users#show_house', as: :show_house # user_id

  patch '/houses/approval_update/:house_id' => 'houses#approval_update',
        as: :approval_update
  patch '/houses/reserve_update/:house_id' => 'houses#reserve_update',
        as: :reserve_update
  # For details on the DSL available within this file, see
  # https://guides.rubyonrails.org/routing.html
end

app/controllers/addresses_controller.rb
# frozen_string_literal: true

class AddressesController < ApplicationController
  before_action :set_address, only: %i[show edit update destroy]
  before_action :authenticate_user!
  def index
    @addresses = Address.all
  end

  def show; end

  def new
    @address = Address.new
  end

  def edit
    @house = House.find_by(id: params[:house_id])
  end

  def create
    @address = Address.new(address_params)
    @address.house_id = params[:house_id].to_i
    current_user.add_role :landlord unless current_user.has_role? :landlord
    respond_to do |format|
      if @address.save
        @house = Address.eager_load(house: :user)
                        .find_by('houses.id=?', params[:house_id])
        flash[:success] = 'Request is sent to Admin'
        BookingMailer.house_post(@house).deliver
        format.html { redirect_to houses_path }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html do
          redirect_to houses_url,
                      notice: 'House Profile was successfully updated.'
        end
      else
        format.html { render :edit }
      end
    end
  end

  def destroy; end

  private

  def set_address
    @address = Address.find_by(house_id: params[:house_id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def address_params
    params.require(:address).permit(:house_address, :state, :city, :area,
                                    :pincode)
  end
end

app/views/addresses/edit.html.erb
<% if @house.user_id == current_user.id %>
<%= form_with(model: @address, local: true, url: house_address_path(@address.house.id)) do |form| %> 
    <div class="container">  
      <div class="row">
        <div class="col-md-2">
         <%= form.label :House_Address %>
        </div>
        <div class="col-md-10">
          <%= form.text_area :house_address %>
        </div>
      </div>
      
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :State %>
        </div>
        <div class="col-md-10">
          <%= form.select :state, options_for_select(CS.states(:in).map { |c| [c[1], c[0]] }, @address.state ) %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :City %>
        </div>
        <div class="col-md-10">
  
          <%= form.select :city, options_for_select(CS.cities(@address.state), @address.city) %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :Area %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :area %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-2">
          <%= form.label :Pincode %>
        </div>
        <div class="col-md-10">
          <%= form.text_field :pincode %>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-1">
        </div>
        <div class="col-md-11">
          <%= form.submit :Submit, class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>  
      
  <br>
  <%= link_to 'Back', edit_house_path(@address.house_id) %>
  <% end %>

app/views/addresses/new.html.erb
<% if @address.errors.any? %>

      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @address.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>

  <% end %>
<%= form_with(model: @address,url: house_addresses_path(params[:house_id]),method: :post, local: true) do |form| %> 

  <div class="row">
    <div class="col-md-2">
      <%= form.label :Address %>
    </div>
    <div class="col-md-10">
      <%= form.text_area :house_address %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :State %>
    </div>
    <div class="col-md-10">
      <%= form.select :state, options_for_select(CS.states(:in).map { |c| [c[1], c[0]] } ),{:prompt => 'Select State'}, class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :city %>
    </div>
    <div class="col-md-10">
      <%= form.select :city, options_for_select([] ),{:prompt => 'Select City'}, class: "btn btn-outline-secondary" %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :Area %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :area %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
      <%= form.label :Pincode %>
    </div>
    <div class="col-md-10">
      <%= form.text_field :pincode %>
    </div>
  </div>

  <br>

  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-10">
      <%= form.submit :Submit, class: "btn btn-primary" %>
    </div>
  </div>

<% end %>         
<br>